default_context:
  description: "A Django backend project."
  author_name: "Maciej Borkowski"
  domain_name: "example.com" 
  email: borkowski.mac@gmail.com,
  version: "0.1.0"
  open_source_license: "Not open source"
  username_type: "email"
  timezone: "UTC"
  windows: "n"
  editor: "VS Code"
  use_docker: "y"
  postgresql_version: "18"
  cloud_provider: "None"
  mail_service: "Other SMTP" #  other for gmail
  rest_api: "Django Ninja"
  use_async: "n"
  frontend_pipeline: "None" # none for React
  use_celery: "y"
  use_mailpit: "y" # can test gmail
  use_sentry: "y" # next to grafana
  use_whitenoise: "y"
  use_heroku: "n"
  ci_tool: "Github"
  keep_local_envs_in_vcs: "n"
  debug: "n"
