
# test: Run pytest in container
test *args:
    @docker compose run --rm django uv run pytest {{args}}

# typing: Check typing in containe
type args=".":
    @docker compose run --rm django uv run mypy  {{args}}

# run: run a command in django container
run +args:
    @docker compose run --rm django {{args}}

# exec: exec a command in running django container
exec +args:
    @docker compose exec django {{args}}

# dcp: docker compose production 
dcp +args:
    @docker compose -f docker-compose.production.yml {{args}}

# dc: docker compose local
dc +args:
    @docker compose -f docker-compose.local.yml {{args}}
